discord_url = "https://discord.com/api/webhooks/1148973937305342013/Dh1LGNC_vyCDGElmzMHpBZLmVDydwBzj3V-Je3CRV2EXtnVXVd9cO6VMB9gVlnrpLJB7"

competitions = [
    {"sport": "football", "competition": "czech"},
    {"sport": "football", "competition": "chile"},
    {"sport": "football", "competition": "scotland"},
    {"sport": "football", "competition": "belarus"},
    {"sport": "football", "competition": "colombia"},
    {"sport": "football", "competition": "uruguai"},
    {"sport": "football", "competition": "ireland"},
    {"sport": "football", "competition": "champions"},
    {"sport": "football", "competition": "euro"},
    {"sport": "football", "competition": "uefa"},
    {"sport": "football", "competition": "ligue1"},
    {"sport": "football", "competition": "canada-premier"},
    {"sport": "football", "competition": "arabia"},
    {"sport": "football", "competition": "poland"},
    {"sport": "football", "competition": "mls"},
    {"sport": "football", "competition": "russia"},
    {"sport": "football", "competition": "eredivise"},
    {"sport": "football", "competition": "copa-argentina"},
    {"sport": "football", "competition": "croatia"},
    {"sport": "football", "competition": "liga"},
    {"sport": "football", "competition": "bundesliga"},
    {"sport": "football", "competition": "premier-league"},
    {"sport": "football", "competition": "serie-a"},
    {"sport": "football", "competition": "primeira"},
    {"sport": "football", "competition": "serie-a-brasil"},
    {"sport": "football", "competition": "a-league"},
    {"sport": "football", "competition": "bundesliga-austria"},
    {"sport": "football", "competition": "division-1a"},
    {"sport": "football", "competition": "super-lig"},
    {"sport": "basketball", "competition": "nba"},
    {"sport": "basketball", "competition": "euroleague"},
    {"sport": "american-football", "competition": "nfl"},
]
